spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss_db
    username: root
    password: 2413
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true